
http:
  port: "8081"
  

accounts:
  host: "account-nr-y6fb6b.5sc6y6-4.usa-e2.cloudhub.io"
  port: "80"
  basepath: "/api"
  protocol: "HTTP"
  client_id: "8abe4ebf6ea043f2b04056bc3951b6df"
  client_secret: "7C67b22BCF63449F80d0b3eD51a3a621"